### ISSUE TITLE
Milestones & Design Check-Ins

### ISSUE THREAD

**Issue by Stebalien** [protocol/web3-dev-team#91]
# Background

Currently:

1. Project proposals go into very little detail because that detail isn't usually known ahead of time.
2. When these details (e.g., detailed problem definitions, design proposals, etc.) become known, there's no forum/check-in to actually discuss and give feedback on these details.

This is making it difficult for teams other than the team directly working on the project to:

- Validate that the correct problem is being solved (e.g., after investigation, benchmarking, problem definition, etc.).
- Comment on the proposed design (once it exists).

# Proposal

I'd like project proposals to include specific milestones & check-in points where investigation & design artifacts are linked into the proposal for further analysis and discussion. For example, a project might have the following steps:

> 1. Investigate deal failures. CHECK-IN: create a report on common deal failure causes and solicit feedback.
> 2. Explore the design space. CHECK-IN: create a high-level design-space document that compares possible solutions and their trade-offs (and solicit feedback)
> 3. Design the solution. CHECK-IN: post a proposed design and solicit feedback.

This way, the stewards team, product teams, and other teams (community?) can give missing context and feedback early and often without having to actively watch everything going on in every project team.

**Bonus:** we could maybe set timelines for these milestones :grin:?
**Note:** Some projects may not need any check-ins (e.g. if there are no unknowns) or just a single check-in for the design itself.

# Alternatives

## Mini-projects

Instead of check-ins, we could just define smaller projects and project "sequences". That is:

1. Project 1: Investigate deal failures. Output: Create a report on common deal failure causes and solicit feedback.
2. Project 2: Explore the deal failure design space. Output: Create a high-level design-space document that compares possible solutions and their trade-offs.
3. Project 3: Design a solution for deal failure problem X. Output: A design proposal Y.
4. Project 4: Implement proposal Y.

However, I'm concerned that this will lead to too much planning overhead and isn't really worth it.

## RFC Process

The stewards team has been working on an RFC process for both internal and external use. A key goal of the RFC process is to again provide a sort of pre-work "check-in" where designs can be discussed.

Unfortunately, said RFC process is currently pretty heavy weight and probably overkill for what we really need at this point.

# Drawbacks

This might introduce a small pause between creating design artifacts and actually moving forward, but I think we can make this move forward pretty quickly.

These check-ins may force us to produce additional design/investigation artifacts which will take time. But I have a hard time seeing that as a drawback.

**Comment by Stebalien** [comment]
cc @momack2 @mikeal 

This came up earlier today when I was grumbling to @BigLep about lack of a design feedback loop. @BigLep suggested a specific design phase in the project pipeline but that morphed into general-purpose milestones/checkpoints when I was writing up this proposal.

Future work includes scheduled weekly design reviews, but just having explicit checkpoints (with artifacts/documents for review) will get us most of the way there (I think).

@BigLep do you think this proposal will solve the problems we were discussing? (an does the proposal make sense?)

**Comment by willscott** [comment]
You frame this as "solicit feedback" but if we do this we should be clear about what we mean:
* do projects have one or some external stakeholders that we identify going into them as people we want to sign off on these things, or is purely an advisory thing?

If it's purely solicited, I worry that we end up in the subsequent week, and then feedback comes in to change or expand scope. Our process is not well-equipped to change direction in response to that sort of feedback within the span of a one month project.

If we're willing to expand project time frames, which results in less clear/larger, then consensus building within the scope of a project will be more important. I'm hesitant to impose more process than we're already putting on ourselves given the current targeted length of projects.

**Comment by Stebalien** [comment]
> You frame this as "solicit feedback" but if we do this we should be clear about what we mean:
> * do projects have one or some external stakeholders that we identify going into them as people we want to sign off on these things, or is purely an advisory thing?

Both, but I mostly care about the former. Projects have external stakeholders anyways, it's just that we currently speed through till the end so we don't have any chance to catch issues before we're "done".

> If it's purely solicited, I worry that we end up in the subsequent week, and then feedback comes in to change or expand scope. Our process is not well-equipped to change direction in response to that sort of feedback within the span of a one month project.

Feedback needs to be timely, ideally with a turn around of days.

> If we're willing to expand project time frames, which results in less clear/larger, then consensus building within the scope of a project will be more important.

Projects start out with a problem to solve, but project proposals rarely discuss how we're going to actually solve these problems. I'm also happy to just break projects into smaller well-defined pieces (see the alternatives) but I figured the approach described here would have less overhead.

> I'm hesitant to impose more process than we're already putting on ourselves given the current targeted length of projects.

At a minimum:

1. The product team needs a way to make sure we're still solving the right problem after a project team does an initial investigation.
2. The stewards team needs a way to give design input before project teams move on to the next step. This is the primary function of the stewards team and something we've been unable to do under the current model.

If you can think of a lighter-weight way to do this, I'm all ears.

**Comment by willscott** [comment]
> If you can think of a lighter-weight way to do this, I'm all ears.

I think more what I want the conversation to include and identify is if we introduce this process, which other parts of the current process can we reduce or replace with it.

**Comment by rvagg** [comment]
An approach I've taken with a couple of my proposals is to scope them as exploratory, i.e. mini initial project for discovery, along with details about the future work behind them. Anything that's sized as `L` (and probably even `M`) should be considered sus and should probably be broken down into pieces or have a way to insert recalibration in the middle.

So perhaps the answer here is something like:

1. Any proposal that is scoped over a certain size (maybe `M`) needs to include milestones as a way to check-in and recalibrate the outcomes and value of continuing as well as updating estimates of future work (because it will always be out). If you're scoping an uber-project then you should be prepared to have its utility questioned and it possibly cancelled part-way through, so plan accordingly.
2. We encourage proposals to aim for the `S` - `M` range and one way to achieve that is to frame a larger job as a discovery project that's spending time coming up with firmer estimates and a clearer plan, which might turn back in to (1) or might spin off to discrete projects.

I'd also like us to be mindful of adding additional process because there's already a lot of busywork in our process that generates data that isn't being consumed in any meaningful way. If we add something extra, maybe we can remove some things too?

**Comment by mikeal** [comment]
This is something that we need to discuss synchronously in the leads meeting. It’s going to consume substantially more time and attention trying to have it in GitHub comments.
