### ISSUE TITLE
How to handle a project proposal that isn't a short term priority

### ISSUE THREAD

**Issue by BigLep** [protocol/web3-dev-team#95]
Per conversation that has happened in [interal PL Slack](https://protocollabs.slack.com/archives/C01L5S4TBPH/p1617297064410500), there is a move to more proactively close project proposals that aren't in our short term priority list.  There were a couple of concerns raised about this around discoverability:

1. By closing without merging, we can't open a directory of proposals and search over them with all the tools there are for searching in files.
2. There isn't an easy way to identify the closed PR's that didn't get selected.  For example, a search like [is:closed project:protocol/web3-dev-team/3](https://github.com/protocol/web3-dev-team/issues?q=is%3Aclosed+project%3Aprotocol%2Fweb3-dev-team%2F3+) doesn't pull these items up because these closed items have been removed from the board.  Example: https://github.com/protocol/web3-dev-team/pull/82

A proposal that was discussed was:

For items that aren't on the short-term priority list:
1. close out the PR with a note that you can re-open it and add a “Review” section like:
```
## Review
### YYYY-MM-DD
$textOnTheCurentState
```
2. Add to a “future” directory
3. Merge it

A couple of notes:
1. We are effectively letting the author's willingness to make these slight updates as a signal for how willingly we are to invest in it for the future vs. just letting it fully closeout.  
2. Putting issues in a different directory makes it easy to distinguish between things we finish and things we flushed out but put on the backlog.

One other thought: for PR's that we're closing because they're not a short-term priority, should we maybe put them in a special column (e.g., "Closed: Not Short Term Priority")?  I'm suggesting this because otherwise it becomes harder for someone to identify which PRs were closed for this reason.  For example, a search like [is:closed -project:protocol/web3-dev-team/3](https://github.com/protocol/web3-dev-team/issues?q=is%3Aclosed+-project%3Aprotocol%2Fweb3-dev-team%2F3+) has other cruft.

If a proposal like the above gets adopted, I assume it results in:
1. Updates to https://github.com/protocol/web3-dev-team/blob/main/README.md
2. Adding some extra text to all the PR's we just closed

Cc'ing @mikeal, @jacobheun, @warpfork, @momack2, @Stebalien as folks who have had engagement in this conversation.

**Comment by BigLep** [comment]
@mikeal @jacobheun : I assume that we'll have followup discussion about how specifically we handle merging PRs in this GitHub issue (per agreement in our internal project leads meeting that we should merge more rather than close).  It seemed like there were different ideas here.  I assume it would be most helpful to have Stewards propose a specific suggestion.  We'll plan on doing this unless we hear otherwise.

**Comment by laurentsenta** [comment]
(triage session)
@BigLep did the follow-up discussion happen? And is this still relevant / priority?

**Comment by BigLep** [comment]
This can be closed.  This was from an attempt in 2021 to show all projects off the org in GitHub.
